# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pydentasarlanan9.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDialogButtonBox,
    QGroupBox, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

from PySide6.QtMultimedia import QCamera, QMediaCaptureSession, QMediaDevices
from PySide6.QtMultimediaWidgets import QVideoWidget
from PySide6.QtWebEngineWidgets import QWebEngineView
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 787)
        self.actionGOOGLE = QAction(MainWindow)
        self.actionGOOGLE.setObjectName("actionGOOGLE")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_3.setGeometry(QRect(490, 0, 231, 191))
        font = QFont()
        font.setFamilies(["Helvetica"])
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(True)
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.label_9.setGeometry(QRect(10, 40, 81, 16))
        font1 = QFont()
        font1.setFamilies(["Helvetica"])
        font1.setPointSize(15)
        font1.setBold(True)
        self.label_9.setFont(font1)
        self.lcdNumber_5 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(110, 30, 111, 31))
        self.lcdNumber_6 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(110, 70, 111, 31))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.label_10.setGeometry(QRect(10, 80, 81, 16))
        self.label_10.setFont(font1)
        self.lcdNumber_7 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(110, 110, 111, 31))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.label_11.setGeometry(QRect(10, 120, 91, 16))
        self.label_11.setFont(font1)
        self.lcdNumber_8 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(110, 150, 111, 31))
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.label_12.setGeometry(QRect(10, 160, 81, 16))
        self.label_12.setFont(font1)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 200, 711, 371))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAutoFillBackground(True)

        # QVideoWidget ekle
        self.videoWidget = QVideoWidget(self.groupBox_5)
        self.videoWidget.setGeometry(QRect(10, 30, 691, 331))

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 231, 191))
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.groupBox.setAutoFillBackground(True)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.label.setGeometry(QRect(10, 30, 81, 16))
        self.label.setFont(font1)
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setGeometry(QRect(90, 20, 131, 41))
        self.comboBox.setFont(font1)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.label_2.setGeometry(QRect(10, 70, 71, 16))
        self.label_2.setFont(font1)
        self.comboBox_2 = QComboBox(self.groupBox)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 60, 131, 41))
        self.comboBox_2.setFont(font1)
        self.comboBox_3 = QComboBox(self.groupBox)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.setGeometry(QRect(90, 100, 131, 41))
        self.comboBox_3.setFont(font1)
        self.lcdNumber = QLCDNumber(self.groupBox)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setGeometry(QRect(100, 140, 111, 31))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.label_3.setGeometry(QRect(10, 110, 61, 16))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.label_4.setGeometry(QRect(10, 150, 81, 16))
        self.label_4.setFont(font1)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.setGeometry(QRect(250, 0, 231, 191))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.lcdNumber_2 = QLCDNumber(self.groupBox_2)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(110, 60, 111, 31))
        self.lcdNumber_3 = QLCDNumber(self.groupBox_2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(110, 100, 111, 31))
        self.lcdNumber_4 = QLCDNumber(self.groupBox_2)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(110, 140, 111, 31))
        self.progressBar = QProgressBar(self.groupBox_2)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setGeometry(QRect(110, 20, 111, 31))
        self.progressBar.setValue(24)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.label_5.setGeometry(QRect(10, 30, 101, 16))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.label_6.setGeometry(QRect(10, 70, 101, 16))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.label_7.setGeometry(QRect(10, 110, 101, 16))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.label_8.setGeometry(QRect(10, 150, 101, 16))
        self.label_8.setFont(font1)
        self.webEngineView = QWebEngineView(self.centralwidget)
        self.webEngineView.setObjectName("webEngineView")
        self.webEngineView.setGeometry(QRect(730, 30, 681, 711))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 580, 711, 161))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(True)
        self.buttonBox = QDialogButtonBox(self.groupBox_4)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setGeometry(QRect(360, 110, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
        self.comboBox_4 = QComboBox(self.groupBox_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.setGeometry(QRect(10, 60, 691, 41))
        self.comboBox_4.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 22))
        self.menuCamera = QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.menubar.addAction(self.menuCamera.menuAction())
        self.menuCamera.addAction(self.actionGOOGLE)

        QMetaObject.connectSlotsByName(MainWindow)

        self.setup_camera()

    def setup_camera(self):
        self.camera = QCamera(QMediaDevices.defaultVideoInput())
        self.capture_session = QMediaCaptureSession()
        self.capture_session.setCamera(self.camera)
        self.capture_session.setVideoOutput(self.videoWidget)
        self.camera.start()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "MainWindow", None))
        self.actionGOOGLE.setText(QCoreApplication.translate("MainWindow", "GOOGLE", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", "GroupBox", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", "Label 1", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", "Label 2", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", "Label 3", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", "Label 4", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", "Camera Feed", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", "GroupBox", None))
        self.label.setText(QCoreApplication.translate("MainWindow", "ComboBox 1", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", "Option 1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", "Option 2", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", "ComboBox 2", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", "Option 1", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", "Option 2", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", "Option 1", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", "Option 2", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", "ComboBox 3", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", "Label 5", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", "GroupBox", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", "Progress Bar", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", "LCD Number 2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", "LCD Number 3", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", "LCD Number 4", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", "GroupBox", None))
        self.menuCamera.setTitle(QCoreApplication.translate("MainWindow", "Camera", None))

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())